--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11/02/2020 19:33:29
-- Server version: 5.5.5-10.4.11-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE fideliza;

--
-- Drop table `imagem`
--
DROP TABLE IF EXISTS imagem;

--
-- Drop table `tipo_docto`
--
DROP TABLE IF EXISTS tipo_docto;

--
-- Drop table `conta_bancaria`
--
DROP TABLE IF EXISTS conta_bancaria;

--
-- Drop table `ocorrencia`
--
DROP TABLE IF EXISTS ocorrencia;

--
-- Drop table `referencia`
--
DROP TABLE IF EXISTS referencia;

--
-- Drop table `cliente`
--
DROP TABLE IF EXISTS cliente;

--
-- Drop table `empregador`
--
DROP TABLE IF EXISTS empregador;

--
-- Drop table `usuario`
--
DROP TABLE IF EXISTS usuario;

--
-- Drop table `empresa`
--
DROP TABLE IF EXISTS empresa;

--
-- Drop table `estado_civil`
--
DROP TABLE IF EXISTS estado_civil;

--
-- Drop table `sexo`
--
DROP TABLE IF EXISTS sexo;

--
-- Set default database
--
USE fideliza;

--
-- Create table `sexo`
--
CREATE TABLE sexo (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

--
-- Create table `estado_civil`
--
CREATE TABLE estado_civil (
  id INT(11) NOT NULL AUTO_INCREMENT,
  descricao VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

--
-- Create table `empresa`
--
CREATE TABLE empresa (
  id INT(11) NOT NULL,
  cnpj VARCHAR(11) DEFAULT NULL,
  razao_social VARCHAR(100) NOT NULL,
  telefone VARCHAR(20) DEFAULT NULL,
  celular VARCHAR(20) DEFAULT NULL,
  email VARCHAR(20) DEFAULT NULL,
  responsavel VARCHAR(100) DEFAULT NULL,
  responsavel_email VARCHAR(100) DEFAULT NULL,
  responsavel_celular VARCHAR(20) DEFAULT NULL,
  data_criacao DATETIME DEFAULT current_timestamp(),
  status INT(1) NOT NULL DEFAULT 1 COMMENT '1 - ativo,2 - inativo, 3 - inadimplente',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `usuario`
--
CREATE TABLE usuario (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  login VARCHAR(20) NOT NULL,
  senha VARCHAR(80) NOT NULL,
  imagem VARCHAR(100) DEFAULT NULL,
  id_empresa INT(11) NOT NULL,
  status VARCHAR(1) NOT NULL,
  acessa_usuario VARCHAR(1) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 22,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

--
-- Create index `login` on table `usuario`
--
ALTER TABLE usuario 
  ADD UNIQUE INDEX login(login);

--
-- Create foreign key
--
ALTER TABLE usuario 
  ADD CONSTRAINT fk_usuario_x_empresa FOREIGN KEY (id_empresa)
    REFERENCES empresa(id);

--
-- Create table `empregador`
--
CREATE TABLE empregador (
  id INT(11) NOT NULL AUTO_INCREMENT,
  razao_social VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  cnpj VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  endereco VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  bairro VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  cidade VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  uf VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  telefone VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

--
-- Create table `cliente`
--
CREATE TABLE cliente (
  id INT(10) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(100) DEFAULT NULL,
  cpf VARCHAR(11) DEFAULT NULL,
  data_nascimento DATE DEFAULT NULL,
  rg VARCHAR(9) DEFAULT NULL,
  data_expedicao DATE DEFAULT NULL,
  orgao_expedidor VARCHAR(6) DEFAULT NULL,
  nome_pai VARCHAR(100) DEFAULT NULL,
  nome_mae VARCHAR(100) DEFAULT NULL,
  naturalidade VARCHAR(100) DEFAULT NULL,
  id_estado_civil INT(11) DEFAULT NULL,
  id_empresa INT(11) DEFAULT NULL,
  id_sexo INT(11) DEFAULT NULL,
  cep VARCHAR(9) DEFAULT NULL,
  endereco VARCHAR(100) DEFAULT NULL,
  numero VARCHAR(6) DEFAULT NULL,
  complemento VARCHAR(100) DEFAULT NULL,
  bairro VARCHAR(100) DEFAULT NULL,
  cidade VARCHAR(100) DEFAULT NULL,
  uf VARCHAR(2) DEFAULT NULL,
  telefone VARCHAR(20) DEFAULT NULL,
  celular VARCHAR(20) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  id_empregador INT(11) DEFAULT NULL,
  profissao VARCHAR(100) DEFAULT NULL,
  data_admissao DATE DEFAULT NULL,
  salario DECIMAL(9, 2) DEFAULT NULL,
  matricula VARCHAR(20) DEFAULT NULL,
  status_emprestimo INT(1) NOT NULL DEFAULT 1 COMMENT '''1-solicitação recebida,2 - em análise,3 - aprovado, 4 - negado''',
  modalidade VARCHAR(2) DEFAULT NULL,
  valor_desejado DECIMAL(12, 2) NOT NULL,
  qtde_parcela_desejada INT(3) DEFAULT NULL,
  valor_aprovado DECIMAL(12, 2) DEFAULT NULL,
  qtde_parcelas_aprovada INT(3) NOT NULL,
  valor_parcelas_aprovada DECIMAL(12, 2) DEFAULT NULL,
  observacoes VARCHAR(400) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 12,
AVG_ROW_LENGTH = 1489,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE cliente 
  ADD CONSTRAINT FK_cliente_x_empregador FOREIGN KEY (id_empregador)
    REFERENCES empregador(id) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE cliente 
  ADD CONSTRAINT fk_cliente_x_empresa FOREIGN KEY (id_empresa)
    REFERENCES empresa(id);

--
-- Create foreign key
--
ALTER TABLE cliente 
  ADD CONSTRAINT fk_cliente_x_sexo FOREIGN KEY (id_sexo)
    REFERENCES sexo(id);

--
-- Create foreign key
--
ALTER TABLE cliente 
  ADD CONSTRAINT fk_cline_estado_civil FOREIGN KEY (id_estado_civil)
    REFERENCES estado_civil(id);

--
-- Create table `referencia`
--
CREATE TABLE referencia (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  telefone VARCHAR(20) NOT NULL,
  observacao VARCHAR(300) NOT NULL,
  id_cliente INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE referencia 
  ADD CONSTRAINT fk_referencia_x_cliente FOREIGN KEY (id_cliente)
    REFERENCES cliente(id);

--
-- Create table `ocorrencia`
--
CREATE TABLE ocorrencia (
  id INT(11) NOT NULL AUTO_INCREMENT,
  id_cliente INT(11) NOT NULL,
  descricao VARCHAR(300) NOT NULL,
  id_usuario INT(11) NOT NULL,
  data_inclusao DATETIME NOT NULL DEFAULT current_timestamp(),
  status_emprestimo VARCHAR(1) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '1-solicitação recebida,2 - em análise,3 - aprovado, 4 - negado',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 40,
AVG_ROW_LENGTH = 682,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE ocorrencia 
  ADD CONSTRAINT fk_ocorrencia_x_cliente FOREIGN KEY (id_cliente)
    REFERENCES cliente(id);

--
-- Create foreign key
--
ALTER TABLE ocorrencia 
  ADD CONSTRAINT fk_ocorrencia_x_usuario FOREIGN KEY (id_usuario)
    REFERENCES usuario(id);

--
-- Create table `conta_bancaria`
--
CREATE TABLE conta_bancaria (
  id INT(11) NOT NULL AUTO_INCREMENT,
  tipo INT(1) DEFAULT NULL COMMENT '1-conta corrente, 2-poupança',
  banco VARCHAR(100) DEFAULT NULL,
  conta VARCHAR(20) DEFAULT NULL,
  dv_conta INT(1) DEFAULT NULL,
  agencia VARCHAR(20) NOT NULL,
  dv_agencia INT(1) DEFAULT NULL,
  observacao VARCHAR(400) NOT NULL,
  id_cliente INT(11) NOT NULL,
  data_abertura DATE DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE conta_bancaria 
  ADD CONSTRAINT fk_conta_x_cliente FOREIGN KEY (id_cliente)
    REFERENCES cliente(id);

--
-- Create table `tipo_docto`
--
CREATE TABLE tipo_docto (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

--
-- Create table `imagem`
--
CREATE TABLE imagem (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  id_cliente INT(11) DEFAULT NULL,
  id_tipo_docto INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE imagem 
  ADD CONSTRAINT fk_imagem_x_cliente FOREIGN KEY (id_cliente)
    REFERENCES cliente(id);

--
-- Create foreign key
--
ALTER TABLE imagem 
  ADD CONSTRAINT fk_imagem_x_tipo_docto FOREIGN KEY (id_tipo_docto)
    REFERENCES tipo_docto(id);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;